version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "gitsubmodule"
    schedule:
        interval: "daily"
    directory: "/"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"