name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

permissions:
  id-token: write  # Required for trusted publishing
  contents: read

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: make install ARGS="--no-root"

    - name: Run Code Checks
      run: make check

    - name: Running Tests
      run: make test

    - name: Build Package
      run: make build

    - name: Upload Package
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: test-and-build
    runs-on: ubuntu-latest
    environment: testing

    permissions:
      id-token: write

    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish to PyPI
    needs: publish-to-testpypi
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write

    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1