name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: poetry install --no-root

    - name: Run Linter
      run: poetry run pylint .

    - name: Find Security Issues
      run: poetry run bandit -r pp_terminal

    - name: Run Type Checking
      run: poetry run mypy .

    - name: Running Tests
      run: poetry run pytest

    - name: Build Package
      if: success()
      run: poetry build